set(FILES
    Include/STWGameplay/ArenaLayout.h
    Include/STWGameplay/ArenaPresentation.h
    Include/STWGameplay/CombatFeedbackPresentation.h
    Include/STWGameplay/CharacterPhysicalState.h
    Include/STWGameplay/EncounterModel.h
    Include/STWGameplay/EnemyCombatModel.h
    Include/STWGameplay/EnemyCollectionModel.h
    Include/STWGameplay/EnemyPresentation.h
    Include/STWGameplay/EnvironmentPresentation.h
    Include/STWGameplay/FixedSimulationClock.h
    Include/STWGameplay/PresentationInterpolation.h
    Include/STWGameplay/PlayerMovementModel.h
    Include/STWGameplay/PlayerCommand.h
    Include/STWGameplay/PlayerCommandHistory.h
    Include/STWGameplay/PlayerPrediction.h
    Include/STWGameplay/PlayerSimulationTypes.h
    Include/STWGameplay/WeaponModel.h
    Include/STWGameplay/STWGameplayTypeIds.h
    Include/STWGameplay/PlayerSliceModel.h
    Include/STWGameplay/SpawnCheckpointModel.h
    Include/STWGameplay/BodycamCameraPresentation.h
    Include/STWGameplay/STWSkeletalCharacterPresentation.h
    Include/STWGameplay/ViewmodelPresentation.h)
